name = "CraftoriaZ"
author = "_Zaraman3_"
version = "2.5.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4368c362991bbfbcfcafd60071a4451e016e510c17ee01dcf4fb838a1ad89ab8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
