name = "CraftoriaZ"
author = "_Zaraman3_"
version = "2.5.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e22df60ab5d188e025ec2511eaa991600dfc3f6b1ed67ef19ad0cf826fb551c0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
