name = "CraftoriaZ"
author = "_Zaraman3_"
version = "2.5.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f4b2441b45d53d872eb9ac00bd4ca670bf735acd4a0a8bef6b46e09d053e2847"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
